# Generated by Django 4.2.16 on 2024-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
