# Generated by Django 4.2.16 on 2024-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_num', models.CharField(max_length=15)),
                ('date_of_event', models.DateField(null=True)),
                ('place_of_event', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Divorce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_hus', models.CharField(max_length=15)),
                ('national_wife', models.CharField(max_length=15)),
                ('date_of_event', models.DateField(null=True)),
                ('place_of_event', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Marrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_hus', models.CharField(max_length=15)),
                ('national_wife', models.CharField(max_length=15, unique=True)),
                ('date_of_event', models.DateField(null=True)),
                ('place_of_event', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=15, null=True, unique=True)),
                ('national_num', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('dad_name', models.CharField(max_length=15, null=True)),
                ('national_dad', models.CharField(max_length=15, null=True)),
                ('mom_name', models.CharField(max_length=15, null=True)),
                ('national_mom', models.CharField(max_length=15, null=True)),
                ('birth_place', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('date_of_issue', models.DateField(null=True)),
                ('place_of_issue', models.CharField(max_length=15, null=True)),
                ('number_of_issue', models.IntegerField(null=True)),
                ('religion', models.CharField(choices=[('muslim', 'muslim'), ('Christian', 'Christian')], default='muslim', max_length=9)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('widower', 'widower')], default='single', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=15, null=True)),
                ('national_num', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('dad_name', models.CharField(max_length=15, null=True)),
                ('national_dad', models.CharField(blank=True, max_length=15, null=True)),
                ('mom_name', models.CharField(max_length=15, null=True)),
                ('national_mom', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_place', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('date_of_issue', models.DateField(null=True)),
                ('place_of_issue', models.CharField(max_length=15, null=True)),
                ('number_of_issue', models.IntegerField(null=True)),
                ('religion', models.CharField(choices=[('muslim', 'muslim'), ('Christian', 'Christian')], default='muslim', max_length=9)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('widower', 'widower')], default='single', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d')),
                ('date_of_event', models.DateField(null=True)),
                ('place_of_event', models.CharField(max_length=15, null=True)),
                ('code', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Widower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_hus', models.CharField(max_length=15)),
                ('national_wife', models.CharField(max_length=15)),
                ('date_of_divorce', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d')),
            ],
        ),
    ]
