# Generated by Django 4.2.16 on 2024-11-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskperson',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskperson',
            name='place_of_event',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
