# Generated by Django 5.1.3 on 2024-12-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_taskperson_date_of_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
