# Generated by Django 4.2.16 on 2024-11-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=15)),
                ('code', models.IntegerField()),
                ('number', models.IntegerField(unique=True)),
                ('person_national_name', models.CharField(max_length=15)),
                ('document_date', models.DateField()),
            ],
        ),
    ]
