# Generated by Django 4.2.16 on 2024-11-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_document_name_remove_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='person_national_num',
            field=models.CharField(max_length=15),
        ),
    ]
