# Generated by Django 4.2.16 on 2024-11-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='second_national_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
