# Generated by Django 4.2.16 on 2024-11-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='name', max_length=15),
            preserve_default=False,
        ),
    ]
