# Generated by Django 4.2.16 on 2024-11-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
