# Generated by Django 4.2.16 on 2024-11-21 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
