# Generated by Django 4.2.16 on 2024-11-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='done',
            new_name='viewd',
        ),
    ]
