# Generated by Django 4.2.16 on 2024-11-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_rename_done_document_viewd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='viewd',
            new_name='viewed',
        ),
    ]
