# Generated by Django 4.2.16 on 2024-11-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_rename_viewd_document_viewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
    ]
