# Generated by Django 4.2.16 on 2024-11-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_delete_mymodel_remove_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
